version: '3'
services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data  
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynetwork

  entrypoint:
    build: 
      context: ./entrypoint
      dockerfile: Dockerfile
    depends_on:
      - database   
    environment:
      DB_HOST: database  
    command: ["sh", "-c", "sleep 10 && node app.js"]
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  pgdata:  
